disabled_rules:
  - file_length
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - implicit_optional_initialization
  - redundant_discardable_let
  - opening_brace
  - unneeded_synthesized_initializer
  - comma
  - unused_closure_parameter

included:
  - PinakleanApp/Sources

excluded:
  - .build
  - Tests
