<file_path>
Pinaklean/.swiftlint.yml
</file_path>

<edit_description>
Create .swiftlint.yml configuration file with default rules and disabled file_length warning to allow CI to run SwiftLint successfully
</edit_description>

disabled_rules:
  - file_length
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - implicit_optional_initialization
  - redundant_discardable_let
  - opening_brace
  - unneeded_synthesized_initializer

included:
  - PinakleanApp/Sources

excluded:
  - .build
  - Tests
