name: Package Validation

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0'

    - name: Validate Package
      working-directory: PinakleanApp
      run: |
        swift package resolve
        swift build --configuration debug
        echo "Package validation completed successfully"
