name: SBOM: CycloneDX

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  sbom-cyclonedx:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SBOM CycloneDX
      run: |
        cd PinakleanApp
        echo "📦 Generating CycloneDX SBOM..."

        # Create basic CycloneDX SBOM for Swift project
        cat > sbom-cyclonedx.json << 'EOF'
        {
          "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
          "bomFormat": "CycloneDX",
          "specVersion": "1.4",
          "serialNumber": "urn:uuid:$(uuidgen)",
          "version": 1,
          "metadata": {
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "tools": [
              {
                "vendor": "SwiftPM",
                "name": "Package Manager",
                "version": "$(swift --version | head -1 | cut -d' ' -f3)"
              }
            ],
            "component": {
              "type": "application",
              "name": "Pinaklean",
              "version": "1.0.0"
            }
          },
          "components": [
            {
              "type": "library",
              "name": "Swift Standard Library",
              "version": "$(swift --version | head -1 | cut -d' ' -f3)"
            }
          ]
        }
        EOF

        echo "✅ CycloneDX SBOM generated successfully"
