name: Security & Guardrail Tests

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  security-guardrail-tests:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Security Guardrail Tests
      run: |
        cd PinakleanApp
        echo "🔒 Running Security Guardrail Tests..."

        # Check for secrets in code
        if grep -r "password\|secret\|token\|key" Sources/ --include="*.swift" | grep -v "test\|example\|dummy"; then
          echo "❌ Potential secrets found in source code"
          exit 1
        fi

        # Check for insecure patterns
        if grep -r "print(" Sources/ --include="*.swift" | grep -v "test"; then
          echo "⚠️ print() statements found in production code"
        fi

        # Check for proper error handling
        swift_files=$(find Sources -name "*.swift")
        for file in $swift_files; do
          if grep -q "try!" "$file"; then
            echo "⚠️ Force try (!) found in $file"
          fi
        done

        echo "✅ Security guardrail tests completed"
