name: swift-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Core Library
        working-directory: PinakleanApp
        run: |
          echo "Building PinakleanCore..."
          swift build --configuration debug --target PinakleanCore

      - name: Build App
        working-directory: PinakleanApp
        run: |
          echo "Building PinakleanApp..."
          swift build --configuration debug --target PinakleanApp

      - name: Run Basic Tests
        working-directory: PinakleanApp
        run: |
          echo "Running basic tests..."
          swift test --parallel --filter "Basic" || echo "No Basic tests found"

      - name: Generate Coverage
        if: always()
        working-directory: PinakleanApp
        run: |
          swift test --enable-code-coverage || true
          mkdir -p coverage
          # Find the actual test binary dynamically
          TEST_BIN=$(find .build -name "*.xctest" -type d | head -n1)
          PROF_FILE=$(find .build -name "default.profdata" | head -n1)
          if [ -n "$TEST_BIN" ] && [ -n "$PROF_FILE" ]; then
            xcrun llvm-cov export \
              "$TEST_BIN/Contents/MacOS/$(basename "$TEST_BIN" .xctest)" \
              -format text \
              -instr-profile "$PROF_FILE" > coverage/coverage.txt || true
          else
            echo "Coverage artifacts not found; creating empty coverage file" > coverage/coverage.txt
          fi

      - name: Upload Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-macos
          path: PinakleanApp/coverage

