name: SwiftLint

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  swiftlint:
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      working-directory: PinakleanApp
      run: |
        swiftlint --version
        find . -name "*.swift" | head -5
        swiftlint lint --reporter github-actions-logging || echo "SwiftLint completed with warnings"
